rancher/opni-ui

assets/styles/base/_basic.scss, product/opni/components/dialogs/EditClusterDialog.vue
=> Fixing the edit cluster modal to scroll labels and properly show the remove button

opensearch_dashboards.json, public/utils/requests.ts
This PR refactors the query to get pod details so it can include events data.
Next would be adding columns for events to the pods breakdown
=> Add Events details

package.json, public/components/Breakdowns/Breakdowns.tsx, public/components/Breakdowns/components/Basic/Basic.tsx, public/components/Breakdowns/components/ControlPlane/ControlPlane.tsx, public/components/Breakdowns/components/Namesapce/Namespace.tsx, public/components/Breakdowns/components/Pod/Pod.tsx, public/components/Breakdowns/components/Rancher/Rancher.tsx, public/components/Bubble/Bubble.js, public/components/InsightsChart/InsightsChart.tsx, public/components/InsightsChart/style.scss, public/components/Keywords/Keywords.tsx, public/components/Keywords/index.ts, public/components/Keywords/style.scss, public/components/Selector/Selector.tsx, public/components/Selector/style.scss, public/pages/Insights/Insights.tsx, public/utils/group.ts, public/utils/requests.ts, yarn.lock
=> Adding keyword filtering

assets/translations/en-us.yaml, product/opni/components/Clusters.vue, product/opni/models/Cluster.ts
=> Updating clusters table column values and headers

product/opni/components/Cluster.vue
=> Changing how we extract the gateway url for the manual install

public/components/Bubble/Bubble.js, public/components/Bubble/style.scss, public/components/EventsTable/EventsTable.tsx, public/components/SideNav/SideNav.tsx, public/components/TemplatesTable/TemplatesTable.tsx, public/components/TemplatesTable/index.ts, public/components/TemplatesTable/style.scss, public/pages/Events/index.ts, public/pages/Main/Main.js, public/pages/Main/index.js, public/pages/Templates/Templates.tsx, public/pages/Templates/index.ts, public/utils/requests.ts
https://github.com/rancher/opni/issues/359
=> Adding log templates page.

assets/translations/en-us.yaml, components/form/KeyValue.vue, product/opni/components/Clusters.vue, product/opni/components/dialogs/CantDeleteClusterDialog.vue, product/opni/components/dialogs/UninstallCapabilitiesDialog.vue, product/opni/models/Cluster.ts, product/opni/utils/requests.ts, product/opni/utils/time.ts
rancher/opni#381
Also fixing label editing
rancher/opni#432
=> Adding cluster capability uninstallation

assets/styles/base/_helpers.scss, assets/translations/en-us.yaml, components/nav/SideNavColumn/Item.vue, components/nav/SideNavColumn/Items.vue, components/nav/SideNavColumn/index.vue, product/opni/components/CapabilityButton.vue, product/opni/components/Cluster.vue, product/opni/components/Clusters.vue, product/opni/components/GrafanaConfig.vue, product/opni/components/LoggingConfig.vue, product/opni/components/Main.vue, product/opni/components/Monitoring.vue, product/opni/components/RoleBindings.vue, product/opni/components/Roles.vue, product/opni/components/SLOs.vue, product/opni/components/dialogs/EditClusterDialog.vue, product/opni/components/dialogs/UninstallCapabilitiesDialog.vue, product/opni/models/Cluster.ts, product/opni/models/Token.ts, product/opni/models/shared.ts, product/opni/pages/Monitoring.vue, product/opni/router.js, product/opni/utils/requests.ts, product/opni/utils/requests/management.ts, product/opni/utils/requests/monitoring.ts, utils/navigation.js
=> Adding the monitoring configuration.

product/opni/components/Monitoring.vue, product/opni/components/Role.vue, product/opni/components/RoleBinding.vue, product/opni/components/SLO.vue, product/opni/router.js
- Endpoint typo
- Missing cancel buttons
- Fixed the role binding redirect back to role bindings
- Switched the duration syntax for the monitoring config
=> Resolving a number of smaller issues

product/opni/components/Cluster.vue, product/opni/components/Clusters.vue, product/opni/components/dialogs/EditClusterDialog.vue, product/opni/components/dialogs/UninstallCapabilitiesDialog.vue, product/opni/models/Cluster.ts, product/opni/models/Config.ts, product/opni/utils/requests.ts
- Fix cluster labels not showing correctly.
- Add option to isntall via OCI image.
- Add ability to use a configured image registry for install commands
- Increase generated token ttl to 60 mins
- Use the configuration hostname for the gateway address when creating a cluster
rancher/opni#602
rancher/opni#606
rancher/opni#608
rancher/opni#607
rancher/opni#605
=> A number of fixes and new features

product/opni/components/Cluster.vue, product/opni/components/SLOs.vue
=> Fix install command and add monitoring install wall to slos

public/components/Breakdowns/Breakdowns.tsx, public/components/Breakdowns/components/Basic/Basic.tsx, public/components/Breakdowns/components/ControlPlane/ControlPlane.tsx, public/components/Breakdowns/components/Longhorn/Longhorn.tsx, public/components/Breakdowns/components/Namesapce/Namespace.tsx, public/components/Breakdowns/components/Pod/Pod.tsx, public/components/Breakdowns/components/Rancher/Rancher.tsx, public/utils/format.ts, public/utils/requests.ts
Show anomalies for namespace and pod tabs
Fix a formatting issue where numbers were rounded incorrectly Rename pod and namespace to have a workload prefix Give a message about enabling workload insights if there are no logs for pods and namespaces
=> Making changes to workload breakdowns

public/components/EventsTable/EventsTable.tsx, public/components/Filters/EventsFilter/EventsFilter.tsx, public/components/Selector/Selector.tsx, public/pages/Events/Events.tsx
=> Fixing events filtering

product/opni/components/Clusters.vue, product/opni/components/dialogs/CancelUninstallCapabilitiesDialog.vue, product/opni/models/Cluster.ts, product/opni/utils/requests.ts
=> Enabling the ability to cancel a capability uninstall

assets/translations/en-us.yaml, product/opni/components/Alarm.vue, product/opni/components/Alarms.vue, product/opni/components/Endpoints.vue, product/opni/components/SLOs.vue, product/opni/pages/Alarm.vue, product/opni/pages/Alarms.vue, product/opni/router.js
- Endpoints are now properly gated
- SLOs are now properly gated
- Changed condition to alarm
- Alarm type now only shows kube if  monitoring is enabled
=> Bug fixes and changes to alerts

product/opni/components/Alarm.vue, product/opni/components/AlertingOverview.vue, product/opni/components/AttachedEndpoints.vue, product/opni/components/SLO.vue, product/opni/models/alerting/Condition.ts, product/opni/nuxt.config.js
- Alerting Overview now gated by alerting backend
- Fixed editing for alarms
- Changed default values for attached alert endpoints
- fixed kubestate choices
=> Several small alerting fixes

product/opni/utils/requests.ts
- Don't delay if we don't delete data
- Only delay by 1min if we delete the data
rancher/opni#806
=> Update how we set the initialDelay of capability uninstall

package.json, public/components/InsightsChart/InsightsChart.tsx, public/utils/requests.ts, yarn.lock
=> Fixing some issues that came about due to the opensearch upgrade

components/nav/SideNavColumn/Items.vue, layouts/standalone.vue
Safari didn't support the Array method findLastIndex so i'm using my own function now. 
rancher/opni#898
=> Making a fix so this app will run in safari

product/opni/components/AlertingOverview.vue
Switching from Agent Disconnect to Agent Capability Unhealthy.
rancher/opni#1006
=> Updating alerting overview tooltip

assets/translations/en-us.yaml, components/SortableTable/THead.vue, product/opni/components/CapabilityTable.vue, product/opni/components/Clusters.vue
=> Improving the consistency of Cluster/Agent name and id labeling

product/opni/components/Cluster.vue
=> Setting a name when adding an agent so we can disambiguate which cluster was added

public/components/AnomalyChart/AnomalyChart.tsx, public/components/InsightsChart/InsightsChart.tsx, public/utils/format.ts
=> Adding the date to the x axis labels

product/opni/components/LoggingBackend/index.vue
=> Remove the external url field from the logging backend

assets/translations/en-us.yaml, components/formatter/Icon.vue, product/opni/components/Clusters.vue, product/opni/models/Cluster.ts, product/opni/utils/requests/management.ts
https://github.com/rancher/opni/issues/1166
=> Adding a local badge to the agents table

public/utils/requests.ts
https://github.com/orgs/rancher/projects/36/views/1?pane=issue&itemId=22844352
=> Switching to use the new field names when querying for pods and namespaces

assets/translations/en-us.yaml, product/opni/components/LogAnomalyBackend.vue, product/opni/components/PretrainedModels.vue, product/opni/components/WorkloadModelConfig.vue, product/opni/pages/LogAnomalyBackend.vue, product/opni/pages/PretrainedModels.vue, product/opni/router.js
https://github.com/rancher/opni/discussions/1001
resolves rancher/opni#1248
=> Making UX changes for AIOps

public/components/Breakdowns/Breakdowns.tsx, public/components/EventsTable/EventsTable.tsx, public/components/Filters/EventsFilter/EventsFilter.tsx, public/components/Selector/Selector.tsx, public/pages/Events/Events.tsx, public/pages/Insights/Insights.tsx, public/pages/Templates/Templates.tsx, public/utils/group.ts, public/utils/requests.ts
=> Updated to the areas of the app that display cluster id to now make use of cluster name when available

product/opni/components/WorkloadModelConfig.vue
=> Hiding the percentage if the backend doesn't provide it for training

public/utils/requests.ts
=> Fixing the cluster_id in filters

components/form/RadioButton.vue, components/form/RadioGroup.vue, product/opni/components/AlertingBackend.vue
https://github.com/orgs/rancher/projects/36/views/1?pane=issue&itemId=26728285
=> Switching to a radiogroup with tooltips for Alerting backend

pkg/opni/components/WorkloadModelConfig.vue
https://github.com/rancher/opni/issues/1377
=> Disabling the clear watchlist button if we're in the middle of training

pkg/opni/components/AlertingBackend.vue, pkg/opni/components/Backend.vue, pkg/opni/components/LoggingBackend/index.vue, pkg/opni/components/MonitoringBackend/index.vue, pkg/opni/components/WorkloadModelConfig.vue, pkg/opni/l10n/en-us.yaml, pkg/opni/models/Capability.ts, pkg/opni/models/Cluster.ts, pkg/opni/models/MetricCapability.ts, pkg/opni/utils/requests/capability.ts, pkg/opni/utils/requests/node-configuration.ts
https://github.com/orgs/rancher/projects/36/views/1?pane=issue&itemId=27390729
=> Adding the ability to display and change the metrics capability provider

pkg/opni/models/Capability.ts
=> Fix capability status messages

pkg/opni/components/Flyout.vue
Fixes https://github.com/rancher/opni/issues/1446
=> Fix flyout position to always be anchored to the bottom of the window

pkg/opni/components/Agent.vue, pkg/opni/components/Cluster.vue
https://github.com/rancher/opni/issues/1466
=> Removing the crd from the install command on the agents page
